# Orb 'circleci/android@0.2.1' resolved to 'circleci/android@0.2.1'
version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-29
    steps:
    - checkout
    - run:
        command: ./gradlew build
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# 
# orbs:
#   android: circleci/android@0.2.1
# 
# jobs:
#   build:
#     executor: android/android
# 
#     steps:
#       - checkout
#       - run:
#           command: ./gradlew build